version: '3.8'

services:
  # Existing services
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_DB: quantflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  quantflow-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@timescaledb:5432/quantflow
      - REDIS_URL=redis://redis:6379
    depends_on:
      - timescaledb
      - redis

  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    depends_on:
      - quantflow-app

  # Microservices
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  data-ingestion:
    build: ./services/data-ingestion
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
      - timescaledb

  storage:
    build: ./services/storage
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:postgres@timescaledb:5432/quantflow
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
      - timescaledb

  analysis:
    build: ./services/analysis
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka

  trading:
    build: ./services/trading
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka

  ai-agent:
    build: ./services/ai-agent
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - KAFKA_BROKERS=kafka:9092
      - DATA_INGESTION_URL=http://data-ingestion:3001
      - STORAGE_URL=http://storage:3002
      - ANALYSIS_URL=http://analysis:3003
      - TRADING_URL=http://trading:3004
    depends_on:
      - kafka
      - data-ingestion
      - storage
      - analysis
      - trading

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - data-ingestion
      - storage
      - analysis
      - trading
      - ai-agent

  # Enhanced QuantFlow Binance Futures Service
  binance-futures:
    build: ./services/binance-futures
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    depends_on:
      - kafka
      - redis

volumes:
  timescaledb_data:
  node_red_data: