version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb-test
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=crypto_prices
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - timescaledb_data_test:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  timescaledb_data_test: