version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: quantflow-timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quantflow
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: quantflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  quantflow-app:
    build: .
    container_name: quantflow-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@timescaledb:5432/quantflow
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - timescaledb
      - redis
    restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    container_name: quantflow-nodered
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    depends_on:
      - quantflow-app
    restart: unless-stopped

volumes:
  timescaledb_data:
  redis_data:
  node_red_data: